spring:
  application:
    name: gateway-service
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml?group=DEFAULT_GROUP&refreshEnabled=true
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
        namespace: ${NACOS_NAMESPACE:}
      config:
        server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
        namespace: ${NACOS_NAMESPACE:}
        group: DEFAULT_GROUP
        file-extension: yaml
        refresh-enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: shop-service-route
          uri: lb://shop-service
          predicates:
            - Path=/shop/**
          filters:
            - StripPrefix=1

server:
  port: ${SERVER_PORT:8088}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
